/** @jsxImportSource theme-ui */
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import { annotate } from "rough-notation";

export default function Home() {
  useEffect(() => {
    const anchorElements = document.querySelectorAll(".anchor");
    anchorElements.forEach((e) => {
      const annotation = annotate(e, {
        type: "underline",
        iterations: 2,
        padding: ["3px", 0, 0, 0],
        animationDuration: 1000,
        strokeWidth: 2,
      });
      annotation.show();
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Ansh C</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.col}>
            <h1 className={styles.mega} sx={{ color: "accent" }}>
              Hello,
            </h1>
            <h1 sx={{ color: "text" }}>I'm Ansh Chauhan.</h1>
            <p sx={{ color: "text" }}>
              A{" "}
              <Link href={"/dev"}>
                <a
                  sx={{
                    "&:hover": {
                      color: "accent",
                    },
                  }}
                  className="anchor"
                >
                  Web Developer
                </a>
              </Link>
              {", "}
              <Link href={"/design"}>
                <a
                  sx={{
                    "&:hover": {
                      color: "accent",
                    },
                  }}
                  className="anchor"
                >
                  Graphic Designer
                </a>
              </Link>
              {", "}
              <Link href={"/coffee"}>
                <a
                  sx={{
                    "&:hover": {
                      color: "accent",
                    },
                  }}
                  className="anchor"
                >
                  Home Barista
                </a>
              </Link>
              {"."}
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
