/** @jsxImportSource theme-ui */
import Head from 'next/head'
import Link from 'next/link'
import { FaLongArrowAltRight } from 'react-icons/fa'
import { annotate } from 'rough-notation'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'

export default function Home() {
  useEffect(()=>{
    const description = document.querySelector('#desc');
    const descAnnotation = annotate(description, { type: 'box', color: "#92bcea" });
    descAnnotation.show() 
    const icons = document.querySelectorAll('.icon')
    icons.forEach((icon)=>{
      const annotation = annotate(icon, { type: 'underline', color: "#92bcea" });
      icon.addEventListener('mouseover', ()=> {
        annotation.show()
      });
      icon.addEventListener('mouseout', ()=> {
        annotation.hide()
      })
    })
  }, [])
  const customStyles = {
    icon: {
      marginRight: '10px',
    }
  }
  return (
    <div className={styles.container}>

      <Head>
        <title>Ansh's Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p sx={{ color: "text" }}>Welcome to my digital canvas. A collection of <span id="desc">design, code, and expression</span> in one website. While you're around, feel free to check out my:</p>
        <ul>
          <li  sx={{ color: "grey", ':hover': { color: "accent" } }}>
            <Link href="/www">
              <a><FaLongArrowAltRight style={customStyles.icon}/><span className="icon"> Web Development Projects</span></a>
            </Link>
          </li>
          <li  sx={{ color: "grey", ':hover': { color: "accent" } }}>
            <Link href="/design">
              <a><FaLongArrowAltRight style={customStyles.icon}/><span className="icon"> Graphic Design Portfolio</span></a>
            </Link>
          </li>
          <li  sx={{ color: "grey", ':hover': { color: "accent" } }}>
            <Link href="/resume">
              <a><FaLongArrowAltRight style={customStyles.icon}/><span className="icon"> Resume</span></a>
            </Link>
          </li>
        </ul>
      </main>  
    </div>
  )
}
